name: ems
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: ^3.5.1
  # environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kanban_board:
    path: ./kanban_board
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get_cli: ^1.8.1
  get: ^4.6.6
  sp_util: ^2.0.3
  intl: ^0.19.0
  fluid_bottom_nav_bar: ^1.4.0
  date_field: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  path: ^1.9.0
  dio: ^5.7.0
  cuberto_bottom_bar: ^3.1.0
  geolocator: ^13.0.1
  month_year_picker: ^0.4.0+1
  flutter_localization: ^0.2.2
  mat_month_picker_dialog: ^1.1.2
  animated_bottom_navigation_bar: ^1.3.3
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  # google_maps_flutter: ^2.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/blucard.png
    - assets/images/prpcard.png
    - assets/images/avauser.png
    - assets/images/bluecard.png
    - assets/images/greencard.png
    - assets/images/orangecard.png
    - assets/images/redcard.png
  fonts:
    - family: Luxora
      fonts:
        - asset: assets/fonts/LuxoraGrotesk-Regular.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
